# Generated by Django 6.0.6 on 2026-06-27 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_number', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=4)),
                ('expiry_month', models.IntegerField()),
                ('expiry_year', models.IntegerField()),
                ('cardholder_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('spending_limit', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('daily_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_four', models.CharField(max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
